name: Sample Workflows

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Setup Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          python a.py
